### ISSUE TITLE
Restricting the minute field options to every 15 mins

### ISSUE THREAD

**Issue by charlie-litchfield-red** [abichinger/vue-js-cron#8]
Hi @abichinger, I was wondering whether it is possible to restrict the minutes field to every 15 minutes.
I have used the following code for the minuteItems:

```
const minuteItems = () => {
        let res = []
        for(let i of cronVuetify.util.range(0, 59, 15)) {
            const item = {
                text: cronVuetify.util.pad(i, 2),
                alt: i+'',
                value: i
            }
            res.push(item)
        }
        return res
    }
```

However, this results in the dropdown for the minutes menu looking like the following
![image](https://user-images.githubusercontent.com/108408637/190680199-91ae756b-a606-4624-93f4-a710daf33c40.png)
Despite this, the correct numbers (0, 15, 30, 45) are inputted into the cron expression when the corresponding option is clicked.

I was also wondering whether there is a minimum time period property, perhaps that can be added to the validation?

Any advice on resolving this would be much appreciated.

**Comment by abichinger** [comment]
Hello @charlie-litchfield-red, thank you for giving my cron component a shot :)

I was able to reproduce the error on my end and found out that part of the number is hidden.
This is caused by v-list-item, which sets the css property `overflow` to `hidden`.

PLACEHOLDER should fix this issue. Please let me know if it works for you.

In addition it is required to import `vuetify.css`
```js
import '@vue-js-cron/vuetify/dist/vuetify.css'
```

**Comment by charlie-litchfield-red** [comment]
Thank you very much for looking at this. All is now working as expected
